CREATE TABLE Ordina
(
	IdOrdine INT PRIMARY KEY IDENTITY,
	IdUtente INT FOREIGN KEY REFERENCES Utente(IdUtente) ON DELETE CASCADE,
	IdProdotto INT FOREIGN KEY REFERENCES Prodotto(IdProdotto) ON DELETE CASCADE
)