CREATE TABLE Utente 
(
	IdUtente INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR (64) NOT NULL,
	Cognome VARCHAR (64) NOT NULL,
	Username VARCHAR (64) UNIQUE NOT NULL,
	Password VARCHAR (32) NOT NULL
)